### ISSUE TITLE
PHP Fatal error for one-way SOAP operations

### ISSUE THREAD

**Issue by karen-nalbandian-wub** [goetas-webservices/wsdl2php#1]
Hello,
First of all, thank you for this great library!

I noted that it generates a fatal error when I use a WSDL containing one-way operation (https://www.w3.org/TR/wsdl#_one-way). Probably this is due to the inconditional `$this->visitMessage($operation->getOutput(), 'output', $operation, $service);` in `src/Generation/PhpSoapConverter.php` and `src/Generation/JmsSoapConverter.php`.

Kind of quick fix could be:

``` php
if (null !== ($output = $operation->getOutput())) {
    $this->visitMessage($output, 'output', $operation, $service);
}
```

**Comment by goetas** [comment]
The solution looks good, can you make a pull request?

**Comment by goetas** [comment]
fixed with https://github.com/goetas-webservices/wsdl2php/commit/8cd0134f87593ed0c8142ed8e581ae9748b169e6
