### ISSUE TITLE
GoetasWebservices\SoapServices\Metadata\Envelope\Envelope does not appear to exist

### ISSUE THREAD

**Issue by snow-ee** [goetas-webservices/wsdl2php#13]
I was using the goetas-webservices/soap-client to generate an implementation for a Salesforce client, using the latest version. In this generated code, some of the Classes implemented **GoetasWebservices\SoapServices\Metadata\Envelope\Envelope**. This class does not exist in our installation nor could I find it in your github organisation. In the end I simply commented out [line 78 of PhpSoapConverter](https://github.com/goetas-webservices/wsdl2php/blob/master/src/Generation/PhpSoapConverter.php#L78) and was able to generate a working client. I'll admit that our project does add some quirks/tweaks to the generated code, but I don't think this problem is a part of that.

In our installation we composer require "goetas-webservices/soap-client": "^0.2.9", "goetas-webservices/wsdl2php": "^0.5.1", this leads to the following installed packages:

- soap-client@v0.2.9
- wsdl2php@v0.5.1
- xsd2php-runtime@v0.2.13
- soap-reader@v0.3.2
- wsdl-reader@v0.3.6
- wsdl2php@v0.5.1
- xsd-reader@v0.3.7
- xsd2php@0.4.3

Please let me know if you need any more information.

**Comment by goetas** [comment]
the class is defined in https://github.com/goetas-webservices/soap-common/blob/d609a35cca95c93f1e75004e1f1dcb60788e2f95/src/Envelope/Envelope.php

**Comment by goetas** [comment]
are you using goetas-webservices/wsdl2php without the other packages? it might make sense to set the `implements` conditionally only when the interface is found...

**Comment by goetas** [comment]
if you want to sent a PR...
