### ISSUE TITLE
Documentation and related question

### ISSUE THREAD

**Issue by alexis-gruet** [goetas-webservices/wsdl2php#3]
Hi @goetas, 

is this component can works standalone ? or relay on several dependencies ? 

How to start ? What wsdl2php executable is expecting to convert remote WSDL to PHP ? Is there any ( planed ) documentation ? 

Thanks

**Comment by goetas** [comment]
Here https://github.com/goetas-webservices/soap-client-demo you have an example project that uses wsdl2php as component  (and converts a generic wsdl into php and yml metadata)

A "proper" documentation is not yet planned, but i think the demo is a good start.

Feedback?
