### ISSUE TITLE
Can't find the Element named ...

### ISSUE THREAD

**Issue by cinamo** [goetas-webservices/wsdl2php#4]
I've been trying to use the generator on https://sync.severa.com/webservice/S3/API.svc/WSDL?wsdl. It fails consistently with the error Can't find the Element named {http://soap.severa.com/}#GetVersion. What could be the issue here?

Is it possible that the generator does not import the associated XSD's that are referenced through xsd:import?

**Comment by goetas** [comment]
looking at the element `GetVersion` in https://sync.severa.com/webservice/S3/API.svc/WSDL?xsd=xsd0

The definition is a bit weird: 

```xml
<xs:element name="GetVersion">
  <xs:complexType>
    <xs:sequence/>
  </xs:complexType>
</xs:element>
```

Can `sequence` be empty?

**Comment by cinamo** [comment]
According to http://stackoverflow.com/questions/17270086/what-does-xssequence-mean, the <xs:sequence/> is saying that the content of the element (that is, its children) must be an empty sequence of element, that is, there must be no content - the element must be empty (except of course for attributes).

**Comment by goetas** [comment]
tried to convert only the xsd file, and it worked... looks some kind of bug :(

**Comment by goetas** [comment]
fixed in https://github.com/goetas-webservices/xsd-reader/releases/tag/v0.2.5

please run composer update, adding `"goetas-webservices/xsd-reader" : "^v0.2.5"`

**Comment by cinamo** [comment]
Works like a charm, many thanks!
